# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='driver',
            new_name='Driver',
        ),
        migrations.RenameField(
            model_name='pickup',
            old_name='user',
            new_name='User',
        ),
    ]
