# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191122_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='dropOff_lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pickup',
            name='dropOff_lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
