# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20191120_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
