# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20191121_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
