# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20191121_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
