# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
